server:
  port: 7072
  
spring:
  boot:
    message: Hello, Department Service - New Updated with Bus
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/department_service_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Admin@8989}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
